# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    IthoRFT.remote: debug
    custom_components.itho_remote: debug

